FROM ros:noetic

RUN apt update && apt install -y rviz \
         ros-noetic-moveit \
         curl \
         apt-utils \
         python3-pip \
         python-is-python3 \
         net-tools \
         nmap \
         xauth \
         ros-noetic-robot-state-publisher \
         ros-noetic-joint-state-publisher \
         ros-noetic-rqt \
	 ros-noetic-tf-conversions \
         git \
         ros-noetic-usb-cam \
         ros-noetic-camera-calibration \
         htop \
         sudo \
         libxmlrpc-core-c3-dev \
	 wget \
	 fontconfig \
	 unzip

# Descargar la familia Montserrat desde Google Fonts
RUN wget -q -O montserrat.zip https://fonts.google.com/download?family=Montserrat && \
    unzip montserrat.zip -d /usr/share/fonts/truetype/montserrat/ && \
    rm montserrat.zip && \
    fc-cache -f -v

RUN pip install --upgrade pip \
		catkin_tools \
                tensorboard \
                ur_rtde \
                gymnasium==0.29.1 \
                stable-baselines3[extra]==2.2.1 \
                numpy --upgrade \
                scipy \
                opencv-contrib-python \
                mediapipe \ 
                ttkbootstrap \
    		Pillow<10.0

RUN rm -rf /var/lib/apt/lists/* && \
    groupadd -g 1000 laboratorio && \
    useradd -ms /bin/bash laboratorio -u 1000 -g 1000 && \
    echo "laboratorio ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    echo "source /opt/ros/noetic/setup.bash" >> /home/laboratorio/.bashrc && \
    RUN echo 'laboratorio:laboratorio' | chpasswd && \
    chown laboratorio:laboratorio /home/laboratorio && \
    mkdir -p /var/run/laboratorio/1000 && \
    chown laboratorio:laboratorio /var/run/laboratorio/1000

USER laboratorio

ENTRYPOINT [ "sleep", "infinity"]
