// Generated by gencpp from file proyecto_final/FigurasResult.msg
// DO NOT EDIT!


#ifndef PROYECTO_FINAL_MESSAGE_FIGURASRESULT_H
#define PROYECTO_FINAL_MESSAGE_FIGURASRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace proyecto_final
{
template <class ContainerAllocator>
struct FigurasResult_
{
  typedef FigurasResult_<ContainerAllocator> Type;

  FigurasResult_()
    : up()
    , front()  {
    }
  FigurasResult_(const ContainerAllocator& _alloc)
    : up(_alloc)
    , front(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int8_t>> _up_type;
  _up_type up;

   typedef std::vector<int8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int8_t>> _front_type;
  _front_type front;





  typedef boost::shared_ptr< ::proyecto_final::FigurasResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::proyecto_final::FigurasResult_<ContainerAllocator> const> ConstPtr;

}; // struct FigurasResult_

typedef ::proyecto_final::FigurasResult_<std::allocator<void> > FigurasResult;

typedef boost::shared_ptr< ::proyecto_final::FigurasResult > FigurasResultPtr;
typedef boost::shared_ptr< ::proyecto_final::FigurasResult const> FigurasResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::proyecto_final::FigurasResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::proyecto_final::FigurasResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::proyecto_final::FigurasResult_<ContainerAllocator1> & lhs, const ::proyecto_final::FigurasResult_<ContainerAllocator2> & rhs)
{
  return lhs.up == rhs.up &&
    lhs.front == rhs.front;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::proyecto_final::FigurasResult_<ContainerAllocator1> & lhs, const ::proyecto_final::FigurasResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace proyecto_final

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::proyecto_final::FigurasResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::proyecto_final::FigurasResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::proyecto_final::FigurasResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::proyecto_final::FigurasResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::proyecto_final::FigurasResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::proyecto_final::FigurasResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::proyecto_final::FigurasResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d57cf924ec719c04c0d0db866abe5ad7";
  }

  static const char* value(const ::proyecto_final::FigurasResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd57cf924ec719c04ULL;
  static const uint64_t static_value2 = 0xc0d0db866abe5ad7ULL;
};

template<class ContainerAllocator>
struct DataType< ::proyecto_final::FigurasResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "proyecto_final/FigurasResult";
  }

  static const char* value(const ::proyecto_final::FigurasResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::proyecto_final::FigurasResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"int8[] up\n"
"int8[] front\n"
;
  }

  static const char* value(const ::proyecto_final::FigurasResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::proyecto_final::FigurasResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.up);
      stream.next(m.front);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FigurasResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::proyecto_final::FigurasResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::proyecto_final::FigurasResult_<ContainerAllocator>& v)
  {
    s << indent << "up[]" << std::endl;
    for (size_t i = 0; i < v.up.size(); ++i)
    {
      s << indent << "  up[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.up[i]);
    }
    s << indent << "front[]" << std::endl;
    for (size_t i = 0; i < v.front.size(); ++i)
    {
      s << indent << "  front[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.front[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROYECTO_FINAL_MESSAGE_FIGURASRESULT_H
