// Generated by gencpp from file proyecto_final/HandData.msg
// DO NOT EDIT!


#ifndef PROYECTO_FINAL_MESSAGE_HANDDATA_H
#define PROYECTO_FINAL_MESSAGE_HANDDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace proyecto_final
{
template <class ContainerAllocator>
struct HandData_
{
  typedef HandData_<ContainerAllocator> Type;

  HandData_()
    : x(0.0)
    , y(0.0)
    , is_open(false)  {
    }
  HandData_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , is_open(false)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef uint8_t _is_open_type;
  _is_open_type is_open;





  typedef boost::shared_ptr< ::proyecto_final::HandData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::proyecto_final::HandData_<ContainerAllocator> const> ConstPtr;

}; // struct HandData_

typedef ::proyecto_final::HandData_<std::allocator<void> > HandData;

typedef boost::shared_ptr< ::proyecto_final::HandData > HandDataPtr;
typedef boost::shared_ptr< ::proyecto_final::HandData const> HandDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::proyecto_final::HandData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::proyecto_final::HandData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::proyecto_final::HandData_<ContainerAllocator1> & lhs, const ::proyecto_final::HandData_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.is_open == rhs.is_open;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::proyecto_final::HandData_<ContainerAllocator1> & lhs, const ::proyecto_final::HandData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace proyecto_final

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::proyecto_final::HandData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::proyecto_final::HandData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::proyecto_final::HandData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::proyecto_final::HandData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::proyecto_final::HandData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::proyecto_final::HandData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::proyecto_final::HandData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "84735364a2a5c5b5d5c40ee10fa1ddee";
  }

  static const char* value(const ::proyecto_final::HandData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x84735364a2a5c5b5ULL;
  static const uint64_t static_value2 = 0xd5c40ee10fa1ddeeULL;
};

template<class ContainerAllocator>
struct DataType< ::proyecto_final::HandData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "proyecto_final/HandData";
  }

  static const char* value(const ::proyecto_final::HandData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::proyecto_final::HandData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"bool is_open\n"
;
  }

  static const char* value(const ::proyecto_final::HandData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::proyecto_final::HandData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.is_open);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HandData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::proyecto_final::HandData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::proyecto_final::HandData_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "is_open: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_open);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROYECTO_FINAL_MESSAGE_HANDDATA_H
