// Auto-generated. Do not edit!

// (in-package proyecto_final.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class FigurasResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.up = null;
      this.front = null;
    }
    else {
      if (initObj.hasOwnProperty('up')) {
        this.up = initObj.up
      }
      else {
        this.up = [];
      }
      if (initObj.hasOwnProperty('front')) {
        this.front = initObj.front
      }
      else {
        this.front = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type FigurasResult
    // Serialize message field [up]
    bufferOffset = _arraySerializer.int8(obj.up, buffer, bufferOffset, null);
    // Serialize message field [front]
    bufferOffset = _arraySerializer.int8(obj.front, buffer, bufferOffset, null);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type FigurasResult
    let len;
    let data = new FigurasResult(null);
    // Deserialize message field [up]
    data.up = _arrayDeserializer.int8(buffer, bufferOffset, null)
    // Deserialize message field [front]
    data.front = _arrayDeserializer.int8(buffer, bufferOffset, null)
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.up.length;
    length += object.front.length;
    return length + 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'proyecto_final/FigurasResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'd57cf924ec719c04c0d0db866abe5ad7';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result definition
    int8[] up
    int8[] front
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new FigurasResult(null);
    if (msg.up !== undefined) {
      resolved.up = msg.up;
    }
    else {
      resolved.up = []
    }

    if (msg.front !== undefined) {
      resolved.front = msg.front;
    }
    else {
      resolved.front = []
    }

    return resolved;
    }
};

module.exports = FigurasResult;
